export { Hero } from './Hero';
export { Manifesto } from './Manifesto';
export { Capacities } from './Capacities';
export { Lumiere } from './Lumiere';
export { RenovationSignature } from './RenovationSignature';
export { References } from './References';
export { Ambiance } from './Ambiance';
export { Engagement } from './Engagement';
export { QuoteBand } from './QuoteBand';
export { ContactSection } from './ContactSection';
export { CTABand } from './CTABand';
export { Services } from './Services';
export { Clients } from './Clients';
export { ProjectsGallery } from './ProjectsGallery';
export { Testimonials } from './Testimonials';
export type { Testimonial } from './Testimonials';
export { Contact } from './Contact';
export { Team } from './Team';
